---
- name: install apache and upload my web page
  hosts: instance2
  become: yes

  vars:
    sourse_file: ./website/index.html
    dest_file: /var/www/html

  tasks:
  - name: check and print Linux version
    debug: var=ansible_os_family

  - block: #===RedHat===

    - name: install apache RedHat
      yum: name=httpd state=latest

    - name: copy web page to servers RedHat
      copy: src={{ sourse_file }} dest={{ dest_file }} mode=0555
      notify: restart apache RedHat

    - name: start and enable apache "RedHat"
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"


  - block: #===Debian===

    - name: install apache Debian
      apt: name=httpd2 state=latest

    - name: copy web page to servers Debian
      copy: src={{ sourse_file }} dest={{ dest_file }} mode=0555
      notify: restart apache Debian

    - name: start and enable apache "Debian"
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: restart apache RedHat
    service: name=httpd state=restarted

  - name: restart apache Debian
    service: name=apache2 state=restarted
