---
- name: error and handling
  hosts: all
  any_errors_fatal: true
  become: yes

  tasks:
  - name: task 1
    yum: name=treeeee state=latest
    ignore_errors: yes

  - name: task 2
    shell: echo Hello World!
    register: results
    failed_when: results.rc !=0
    
  - debug:
      var: results

  - name: task 3
    shell: echo Privet mir!!!


