---
- name: uninstall default nginx
  hosts: test
  become: yes  

  tasks:
  - name: stop and disable nginx
    service: name=nginx state=stopped enabled=no

  - name: uninstall nginx
    yum: name=nginx state=removed

